title: Burd Tennis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # /tennis     http://katherinedelorme.com/tennis the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site, e.g. http://example.com http://localhost:4000
permalink: /:year/:title/index.html
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
